CREATE SEQUENCE CATEGORY_ID_SEQ START WITH 100001;

CREATE TABLE CATEGORY
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('CATEGORY_ID_SEQ'),
	SITE_ID BIGINT NOT NULL,
	ALICE_CATEGORY_ID BIGINT NULL,
	NAME_EXTRACT1 VARCHAR(128) NOT NULL,
	URL_EXTRACT1 VARCHAR(512) NOT NULL,
	NAME_EXTRACT2 VARCHAR(128) NULL,
	URL_EXTRACT2 VARCHAR(512) NULL,
	NAME_EXTRACT3 VARCHAR(128) NULL,
	URL_EXTRACT3 VARCHAR(512) NULL,
	DISPLAY_ORDER INTEGER NOT NULL,
	EXTRACT_STATUS INTEGER NOT NULL,
	EXTRACT_JOB_ID BIGINT NOT NULL,
	EXTRACTED_DATE TIMESTAMP NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL,
	FOREIGN KEY (SITE_ID) REFERENCES SITE (ID),
	FOREIGN KEY (ALICE_CATEGORY_ID) REFERENCES ALICE_CATEGORY (ID)
);

ALTER SEQUENCE CATEGORY_ID_SEQ OWNED BY CATEGORY.ID;

CREATE INDEX CATEGORY_SITE_ID_IDX ON CATEGORY (SITE_ID, EXTRACT_STATUS);

CREATE TRIGGER CATEGORY_SET_CREATED_DATE BEFORE INSERT ON CATEGORY
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER CATEGORY_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON CATEGORY
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
