CREATE SEQUENCE SITE_ID_SEQ START WITH 1001;

CREATE TABLE SITE
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('SITE_ID_SEQ'),
	STRING_ID VARCHAR(32) NOT NULL,
	COUNTRY_CODE INTEGER NOT NULL,
	DISPLAY_NAME VARCHAR(32) NOT NULL,
	URL VARCHAR(64) NOT NULL,
	DISPLAY NUMERIC(1,0) NOT NULL,
	DISPLAY_WEIGHT INTEGER NOT NULL,
	CURRENCY VARCHAR(16) NOT NULL,
	COOKIES VARCHAR(128),
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL
);

ALTER SEQUENCE SITE_ID_SEQ OWNED BY SITE.ID;

CREATE UNIQUE INDEX SITE_STRING_ID_UNIQUE_IDX ON SITE (STRING_ID);

CREATE INDEX SITE_COUNTRY_IDX ON SITE (COUNTRY_CODE);

CREATE TRIGGER SITE_SET_CREATED_DATE BEFORE INSERT ON SITE
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER SITE_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON SITE
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
