CREATE SEQUENCE PRODUCT_REDIRECT_ID_SEQ START WITH 10000001;

CREATE TABLE PRODUCT_REDIRECT
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('PRODUCT_REDIRECT_ID_SEQ'),
	SITE_STRING_ID VARCHAR(32) NOT NULL,
	PRODUCT_ID BIGINT NOT NULL,
  PAGE_ID VARCHAR(32) NOT NULL, -- referer
  PAGE_NO INTEGER NOT NULL,
  ALICE_CATEGORY VARCHAR(64) NOT NULL,
  POSITION INTEGER NOT NULL,
  IS_MOBILE NUMERIC(1,0) NULL,
  REDIRECT_URL VARCHAR(512) NOT NULL,
	SESSION_ID VARCHAR(128) NOT NULL,
	USER_ID BIGINT NULL,
	USER_LOGIN_SESSION_ID BIGINT NULL,
  REMOTE_ADDRESS VARCHAR(16) NULL,
  USER_AGENT VARCHAR(256) NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL
	-- let's not create foreign keys for a better performance and maintenance
);

ALTER SEQUENCE PRODUCT_REDIRECT_ID_SEQ OWNED BY PRODUCT_REDIRECT.ID;

CREATE INDEX PRODUCT_REDIRECT_SITE_ID_IDX ON PRODUCT_REDIRECT (SITE_ID);

CREATE INDEX PRODUCT_REDIRECT_CREATED_DATE_IDX ON PRODUCT_REDIRECT (CREATED_DATE);

CREATE TRIGGER PRODUCT_REDIRECT_SET_CREATED_DATE BEFORE INSERT ON PRODUCT_REDIRECT
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER PRODUCT_REDIRECT_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON PRODUCT_REDIRECT
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
