CREATE SEQUENCE SUBSCRIPTION_ID_SEQ START WITH 1001;

CREATE TABLE SUBSCRIPTION
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('SUBSCRIPTION_ID_SEQ'),
	NAME VARCHAR(64) NOT NULL,
	TYPE INTEGER NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL
);

ALTER SEQUENCE SUBSCRIPTION_ID_SEQ OWNED BY SUBSCRIPTION.ID;

CREATE UNIQUE INDEX SUBSCRIPTION_NAME_UNIQUE_IDX ON SUBSCRIPTION (NAME);

CREATE TRIGGER SUBSCRIPTION_SET_CREATED_DATE BEFORE INSERT ON SUBSCRIPTION
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER SUBSCRIPTION_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON SUBSCRIPTION
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
