CREATE SEQUENCE USER_ID_SEQ START WITH 1001;

CREATE TABLE USER
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('USER_ID_SEQ'),
	EMAIL_ADDRESS VARCHAR(128) NOT NULL,
	PASSWORD VARCHAR(64) NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	STATUS INTEGER NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL
);

ALTER SEQUENCE USER_ID_SEQ OWNED BY USER.ID;

CREATE UNIQUE INDEX USER_UNIQUE_IDX ON USER (EMAIL_ADDRESS);

CREATE TRIGGER USER_SET_CREATED_DATE BEFORE INSERT ON USER
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER USER_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON USER
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
