CREATE SEQUENCE ALICE_CATEGORY_ID_SEQ START WITH 1001;

CREATE TABLE ALICE_CATEGORY
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('ALICE_CATEGORY_ID_SEQ'),
	NAME VARCHAR(64) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL
);

ALTER SEQUENCE ALICE_CATEGORY_ID_SEQ OWNED BY ALICE_CATEGORY.ID;

CREATE UNIQUE INDEX ALICE_CATEGORY_UNIQUE_IDX ON ALICE_CATEGORY (NAME);

CREATE TRIGGER ALICE_CATEGORY_SET_CREATED_DATE BEFORE INSERT ON ALICE_CATEGORY
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER ALICE_CATEGORY_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON ALICE_CATEGORY
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
