CREATE SEQUENCE USER_VERIFICATION_ID_SEQ START WITH 1000001;

CREATE TABLE USER_VERIFICATION
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('USER_VERIFICATION_ID_SEQ'),
	USER_ID BIGINT NOT NULL,
	EMAIL_ADDRESS_HASH VARCHAR(128) NOT NULL,
	VERIFICATION_CODE VARCHAR(128) NOT NULL,
	VERIFIED CHAR(1) NOT NULL,
	EXPIRATION_DATE TIMESTAMP NOT NULL,
	EMAIL_SENT_DATE TIMESTAMP NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES "USER" (ID)
);

ALTER SEQUENCE USER_VERIFICATION_ID_SEQ OWNED BY USER_VERIFICATION.ID;

CREATE UNIQUE INDEX USER_VERIFICATION_UNIQUE_IDX ON USER_VERIFICATION (EMAIL_ADDRESS_HASH);

CREATE TRIGGER USER_VERIFICATION_SET_CREATED_DATE BEFORE INSERT ON USER_VERIFICATION
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER USER_VERIFICATION_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON USER_VERIFICATION
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
