CREATE SEQUENCE PRODUCT_CLICK_ID_SEQ START WITH 10000001;

CREATE TABLE PRODUCT_CLICK
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('PRODUCT_CLICK_ID_SEQ'),
	SITE_ID BIGINT NOT NULL,
	PRODUCT_ID BIGINT NOT NULL,
  REDIRECT_URL VARCHAR(512) NOT NULL,
	SESSION_ID VARCHAR(128) NOT NULL,
	USER_ID BIGINT NULL,
	USER_LOGIN_SESSION_ID BIGINT NULL,
  REMOTE_ADDRESS VARCHAR(16) NULL,
  USER_AGENT VARCHAR(256) NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL
	-- let's not create foreign keys for a better performance and maintenance
);

ALTER SEQUENCE PRODUCT_CLICK_ID_SEQ OWNED BY PRODUCT_CLICK.ID;

CREATE INDEX PRODUCT_CLICK_SITE_ID_IDX ON PRODUCT_CLICK (SITE_ID);

CREATE INDEX PRODUCT_CLICK_CREATED_DATE_IDX ON PRODUCT_CLICK (CREATED_DATE);

CREATE TRIGGER PRODUCT_CLICK_SET_CREATED_DATE BEFORE INSERT ON PRODUCT_CLICK
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER PRODUCT_CLICK_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON PRODUCT_CLICK
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
