CREATE SEQUENCE USER_FAV_ID_SEQ START WITH 100001;

CREATE TABLE USER_FAV
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('USER_FAV_ID_SEQ'),
	USER_ID BIGINT NOT NULL,
	PRODUCT_ID BIGINT NOT NULL,
	ADD_ON_NAME VARCHAR(128) NOT NULL,
	ADD_ON_PRICE NUMERIC(14,2) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USER (ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

ALTER SEQUENCE USER_FAV_ID_SEQ OWNED BY USER_FAV.ID;

CREATE UNIQUE INDEX USER_FAV_UNIQUE_IDX ON USER_FAV (USER_ID, PRODUCT_ID);

CREATE TRIGGER USER_FAV_SET_CREATED_DATE BEFORE INSERT ON USER_FAV
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER USER_FAV_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON USER_FAV
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
