CREATE SEQUENCE ALICE_CATEGORY_SITE_ID_SEQ START WITH 100001;

CREATE TABLE ALICE_CATEGORY_SITE
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('ALICE_CATEGORY_SITE_ID_SEQ'),
	ALICE_CATEGORY_ID BIGINT NOT NULL,
	SITE_ID BIGINT NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL,
	FOREIGN KEY (ALICE_CATEGORY_ID) REFERENCES ALICE_CATEGORY (ID),
	FOREIGN KEY (SITE_ID) REFERENCES SITE (ID)
);

ALTER SEQUENCE ALICE_CATEGORY_SITE_ID_SEQ OWNED BY ALICE_CATEGORY_SITE.ID;

CREATE UNIQUE INDEX ALICE_CATEGORY_SITE_UNIQUE_IDX ON ALICE_CATEGORY_SITE (ALICE_CATEGORY_ID, SITE_ID);

CREATE TRIGGER ALICE_CATEGORY_SITE_SET_CREATED_DATE BEFORE INSERT ON ALICE_CATEGORY_SITE
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER ALICE_CATEGORY_SITE_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON ALICE_CATEGORY_SITE
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
