CREATE SEQUENCE CATEGORY_PRODUCT_ID_SEQ START WITH 10000001;

CREATE TABLE CATEGORY_PRODUCT
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('CATEGORY_PRODUCT_ID_SEQ'),
	CATEGORY_ID BIGINT NOT NULL,
	PRODUCT_ID BIGINT NOT NULL,
	DISPLAY_ORDER INTEGER NOT NULL,
	EXTRACT_STATUS INTEGER NOT NULL,
	EXTRACT_JOB_ID BIGINT NOT NULL,
	EXTRACTED_DATE TIMESTAMP NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL,
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

ALTER SEQUENCE CATEGORY_PRODUCT_ID_SEQ OWNED BY CATEGORY_PRODUCT.ID;

CREATE UNIQUE INDEX CATEGORY_PRODUCT_UNIQUE_IDX ON CATEGORY_PRODUCT (CATEGORY_ID, PRODUCT_ID);

CREATE TRIGGER CATEGORY_PRODUCT_SET_CREATED_DATE BEFORE INSERT ON CATEGORY_PRODUCT
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER CATEGORY_PRODUCT_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON CATEGORY_PRODUCT
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
