CREATE SEQUENCE JOB_ID_SEQ START WITH 1000001;

CREATE TABLE JOB
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('JOB_ID_SEQ'),
	SITE_ID BIGINT NOT NULL,
	MODE INTEGER NOT NULL,
	STATUS INTEGER NOT NULL,
	START_TIME TIMESTAMP NULL,
	END_TIME TIMESTAMP NULL,
	FOUND_CATEGORY_NO INTEGER NOT NULL,
	FOUND_PRODUCT_NO INTEGER NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL,
	FOREIGN KEY (SITE_ID) REFERENCES SITE (ID)
);

ALTER SEQUENCE JOB_ID_SEQ OWNED BY JOB.ID;

CREATE TRIGGER JOB_SET_CREATED_DATE BEFORE INSERT ON JOB
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER JOB_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON JOB
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
