CREATE SEQUENCE PRICE_HISTORY_ID_SEQ START WITH 10000001;

CREATE TABLE PRICE_HISTORY
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('PRICE_HISTORY_ID_SEQ'),
	PRODUCT_ID BIGINT NOT NULL,
	OLD_PRICE_EXTRACT VARCHAR(64) NOT NULL,
	NEW_PRICE_EXTRACT VARCHAR(64) NOT NULL,
	OLD_PRICE NUMERIC(14,2) NOT NULL,
	NEW_PRICE NUMERIC(14,2) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL,
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

ALTER SEQUENCE PRICE_HISTORY_ID_SEQ OWNED BY PRICE_HISTORY.ID;

CREATE INDEX PRICE_HISTORY_PRODUCT_ID_IDX ON PRICE_HISTORY (PRODUCT_ID);

CREATE TRIGGER PRICE_HISTORY_SET_CREATED_DATE BEFORE INSERT ON PRICE_HISTORY
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER PRICE_HISTORY_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON PRICE_HISTORY
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
