CREATE SEQUENCE USER_SUBSCRIPTION_ID_SEQ START WITH 10000001;

CREATE TABLE USER_SUBSCRIPTION
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('USER_SUBSCRIPTION_ID_SEQ'),
	USER_ID BIGINT NOT NULL,
	SUBSCRIPTION_ID BIGINT NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES "USER" (ID),
	FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION (ID)
);

ALTER SEQUENCE USER_SUBSCRIPTION_ID_SEQ OWNED BY USER_SUBSCRIPTION.ID;

CREATE TRIGGER USER_SUBSCRIPTION_SET_CREATED_DATE BEFORE INSERT ON USER_SUBSCRIPTION
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER USER_SUBSCRIPTION_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON USER_SUBSCRIPTION
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
