CREATE SEQUENCE USER_FAVS_ID_SEQ START WITH 100001;

CREATE TABLE USER_FAVS
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('USER_FAVS_ID_SEQ'),
	USER_ID BIGINT NOT NULL,
	PRODUCT_ID BIGINT NOT NULL,
	ADD_ON_PRICE NUMERIC(14,2) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USER (ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

ALTER SEQUENCE USER_FAVS_ID_SEQ OWNED BY USER_FAVS.ID;

CREATE UNIQUE INDEX USER_FAVS_UNIQUE_IDX ON USER_FAVS (USER_ID, PRODUCT_ID);

CREATE TRIGGER USER_FAVS_SET_CREATED_DATE BEFORE INSERT ON USER_FAVS
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER USER_FAVS_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON USER_FAVS
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
