CREATE SEQUENCE USER_LOGIN_SESSION_ID_SEQ START WITH 10000001;

CREATE TABLE USER_LOGIN_SESSION
(
	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('USER_LOGIN_SESSION_ID_SEQ'),
	USER_ID BIGINT NOT NULL, -- user can log in from multiple machines
	SERIES_ID VARCHAR(64) NOT NULL,
	TOKEN VARCHAR(64) NOT NULL,
	IP_ADDRESS VARCHAR(16) NULL,
	USER_AGENT VARCHAR(256) NULL,
	LAST_LOGIN_DATE TIMESTAMP NOT NULL,
	EXPIRATION_DATE TIMESTAMP NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

ALTER SEQUENCE USER_LOGIN_SESSION_ID_SEQ OWNED BY USER_LOGIN_SESSION.ID;

CREATE UNIQUE INDEX USER_LOGIN_SESSION_ID_UNIQUE_IDX ON USER (SERIES_ID);

CREATE TRIGGER USER_LOGIN_SESSION_SET_CREATED_DATE BEFORE INSERT ON USER_LOGIN_SESSION
FOR EACH ROW EXECUTE PROCEDURE SET_CREATED_DATE();

CREATE TRIGGER USER_LOGIN_SESSION_SET_UPDATED_DATE BEFORE INSERT OR UPDATE ON USER_LOGIN_SESSION
FOR EACH ROW EXECUTE PROCEDURE SET_UPDATED_DATE();
