INSERT INTO site (STRING_ID, COUNTRY_CODE, DISPLAY_NAME, URL, DISPLAY, DISPLAY_WEIGHT, CURRENCY, COOKIES)
VALUES ('toms',1,'TOMS','http://www.toms.com','1',5,'$',''),
('anntaylor',1,'Ann Taylor','http://www.anntaylor.com','1',5,'$','_IntlCtr=US;_IntlCur=USD'),
('anthropologie',1,'Anthropologie','http://www.anthropologie.com','1',5,'$','ICurrency=USD;ILanguage=en-US'),
('williams-sonoma',1,'Williams-Sonoma','http://www.williams-sonoma.com','1',5,'$','INTERNATIONAL=US-USD-1'),
('colehaan',1,'Cole Haan','http://www.colehaan.com','1',5,'$','tradeGlobalGeolocation=US'),
('potterybarn',1,'Pottery Barn','http://www.potterybarn.com','1',5,'$','INTERNATIONAL=US-USD-1'),
('verabradley',1,'Vera Bradley','http://www.verabradley.com','1',5,'$','Country=US;Currency=USD'),
('crateandbarrel',1,'Crate & Barrel','http://www.crateandbarrel.com','1',5,'$','Internationalization=US|USD'),
('madewell',1,'Madewell','https://www.madewell.com','1',5,'$','madewell_country=US'),
('ugg',1,'UGG','http://www.uggaustralia.com','1',5,'$',''),
('michaelkors',1,'Michael Kors','http://www.michaelkors.com','1',5,'$','userPrefLanguage=en_US'),
('toryburch',1,'Tory Burch','http://www.toryburch.com','1',5,'$',''),
('jcrew',1,'J.Crew','https://www.jcrew.com','1',5,'$','jcrew_country=US'),
('sorel',1,'Sorel','http://www.sorel.com','1',5,'$',''),
('eddiebauer',1,'Eddie Bauer','http://www.eddiebauer.com','1',5,'$',''),
('coach',1,'Coach','http://www.coach.com','1',5,'$','');
